#!/usr/bin/env python3
"""
Compile YAML knowledge registry → Cypher seed file.

Usage:
    python scripts/compile_kg.py [--output scripts/neo4j_seed_generated.cypher]
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

try:
    import yaml
except ImportError:
    raise SystemExit("PyYAML required: pip install pyyaml")

REGISTRY_DIR = Path(__file__).resolve().parent / "knowledge_registry"


def _cypher_str(value) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    if isinstance(value, list):
        return json.dumps(value)
    escaped = str(value).replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def compile_nutrients(data: dict) -> list[str]:
    lines = ["// ── Nutrients (from YAML) ──"]
    version = data.get("version", "1.0.0")
    lines.append(f'// Registry version: {version}')
    for n in data.get("nutrients", []):
        nid = n["id"]
        lines.append(f'MERGE (n:Nutrient {{nutrient_id: {_cypher_str(nid)}}})')
        props = (
            f'n.name = {_cypher_str(n["name"])}, '
            f'n.form = {_cypher_str(n["form"])}, '
            f'n.rda = {n["rda"]}, n.ear = {n["ear"]}, n.ul = {n["ul"]}, '
            f'n.dose_unit = {_cypher_str(n["dose_unit"])}, '
            f'n.bioavailability_factor = {n.get("bioavailability_factor", 1.0)}, '
            f'n.loinc_codes = {_cypher_str(n.get("loinc_codes", []))};'
        )
        lines.append(f"SET {props}")
    return lines


def compile_conditions(data: dict) -> list[str]:
    lines = ["// ── Conditions (from YAML) ──"]
    for c in data.get("conditions", []):
        lines.append(
            f'MERGE (c:Condition {{icd10_code: {_cypher_str(c["icd10_code"])}}}) '
            f'SET c.name = {_cypher_str(c["name"])};'
        )
    return lines


def compile_medications(data: dict) -> list[str]:
    lines = ["// ── Medications (from YAML) ──"]
    seen = set()
    for m in data.get("medications", []):
        cui = m["rxnorm_cui"]
        if cui in seen:
            continue
        seen.add(cui)
        atc = f', m.atc_code = {_cypher_str(m["atc_code"])}' if m.get("atc_code") else ""
        lines.append(
            f'MERGE (m:Medication {{rxnorm_cui: {_cypher_str(cui)}}}) '
            f'SET m.name = {_cypher_str(m["name"])}{atc};'
        )
    return lines


def compile_edges(data: dict) -> list[str]:
    lines = ["// ── Edges (from YAML) ──"]
    for edge in data.get("condition_edges", []):
        rel = edge["rel_type"]
        lines.append(
            f'MATCH (c:Condition {{icd10_code: {_cypher_str(edge["condition"])}}}), '
            f'(n:Nutrient {{nutrient_id: {_cypher_str(edge["nutrient"])}}}) '
            f'MERGE (c)-[r:{rel}]->(n) '
            f'SET r.lr = {edge["lr"]}, r.mechanism = {_cypher_str(edge.get("mechanism", ""))}, '
            f'r.grade_weight = {edge.get("grade_weight", 0.75)};'
        )
    for edge in data.get("drug_edges", []):
        rel = edge["rel_type"]
        med = edge["medication"]
        nut = edge["nutrient"]
        set_parts = [
            f'r.lr = {edge.get("lr", 1.0)}',
            f'r.mechanism = {_cypher_str(edge.get("mechanism", ""))}',
        ]
        if edge.get("onset_months") is not None:
            set_parts.append(f'r.onset_months = {edge["onset_months"]}')
        if edge.get("severity"):
            set_parts.append(f'r.severity = {_cypher_str(edge["severity"])}')
        if edge.get("action"):
            set_parts.append(f'r.action = {_cypher_str(edge["action"])}')
        lines.append(
            f'MATCH (m:Medication {{rxnorm_cui: {_cypher_str(med)}}}), '
            f'(n:Nutrient {{nutrient_id: {_cypher_str(nut)}}}) '
            f'MERGE (m)-[r:{rel}]->(n) SET {", ".join(set_parts)};'
        )
    return lines


def compile_all() -> str:
    nutrients = yaml.safe_load((REGISTRY_DIR / "nutrients.yaml").read_text(encoding="utf-8"))
    conditions = yaml.safe_load((REGISTRY_DIR / "conditions.yaml").read_text(encoding="utf-8"))
    medications = yaml.safe_load((REGISTRY_DIR / "medications.yaml").read_text(encoding="utf-8"))
    edges = yaml.safe_load((REGISTRY_DIR / "edges.yaml").read_text(encoding="utf-8"))

    version = nutrients.get("version", "1.0.0")
    parts = [
        "// Generated by scripts/compile_kg.py — do not edit by hand",
        f"MERGE (m:KGMetadata {{id: 'current'}}) SET m.version = {_cypher_str(version)}, "
        "m.updated_at = datetime();",
        *compile_nutrients(nutrients),
        *compile_conditions(conditions),
        *compile_medications(medications),
        *compile_edges(edges),
        'RETURN "YAML registry compiled" AS status;',
    ]
    return "\n".join(parts) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description="Compile YAML KG registry to Cypher")
    parser.add_argument(
        "--output",
        default=str(Path(__file__).resolve().parent / "neo4j_seed_generated.cypher"),
    )
    args = parser.parse_args()
    output = Path(args.output)
    output.write_text(compile_all(), encoding="utf-8")
    print(f"Wrote {output}")


if __name__ == "__main__":
    main()
