name: supplement_engine_etl
version: 1.0.0
config-version: 2

profile: supplement_engine_etl

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

models:
  supplement_engine_etl:
    staging:
      +schema: landing
    patient_realm:
      +schema: public

seeds:
  supplement_engine_etl:
    +schema: landing
