supplement_engine_etl:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('POSTGRES_HOST', 'localhost') }}"
      user: "{{ env_var('POSTGRES_USER', 'supplement') }}"
      password: "{{ env_var('POSTGRES_PASSWORD', 'devpassword') }}"
      port: "{{ env_var('POSTGRES_PORT', '5432') | int }}"
      dbname: "{{ env_var('POSTGRES_DB', 'supplement_db') }}"
      schema: landing
      threads: 4
